apiVersion: apps/v1
kind: Deployment
metadata:
  name: biomark-booking-api
  namespace: biomark-demo
spec:
  selector: 
    matchLabels:
      app: booking-api
  replicas: 1
  template:
    metadata:
      labels:
        app: booking-api
    spec:
      containers:
      - name: booking-api
        image: registry.gitlab.com/biomark/biomark-booking-api:MASTER_527583045
        args: ["bundle exec rails db:migrate && bundle exec puma"]
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: biomark-booking-config        
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biomark-booking-sidekiq
  namespace: biomark-demo
spec:
  selector: 
    matchLabels:
      app: booking-sidekiq
  replicas: 1
  template:
    metadata:
      labels:
        app: booking-sidekiq
    spec:
      containers:
      - name: booking-sidekiq
        image: registry.gitlab.com/biomark/biomark-booking-api:MASTER_527583045
        args: ["bundle exec sidekiq"]
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: biomark-booking-config        
      imagePullSecrets:
      - name: regcred
---      
apiVersion: v1
kind: Service
metadata:
  name: biomark-booking-service
  namespace: biomark-demo
spec:
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  type: NodePort
  selector:
    app: booking-api
