apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: biomark-booking-api
  namespace: biomark-internal
spec:
  selector: 
    matchLabels:
      app: booking-api
  replicas: 1
  template:
    metadata:
      labels:
        app: booking-api
    spec:
      containers:
      - name: booking-api
        image: registry.gitlab.com/biomark/biomark-booking-api:MASTER_520469442
        args: ["bundle exec puma"]
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: biomark-booking-config        
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: biomark-booking-service
  namespace: biomark-internal
spec:
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  type: NodePort
  selector:
    app: booking-api
