version: '3.2'
volumes:
    mysql-data:
        driver: local
services:
    redis:
        image: redis:5.0.9-alpine
        ports:
          - "6379:6379"
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123123
        volumes:
        - "mysql-data:/var/lib/mysql"
        ports:
        - "3306:3306"
    sidekiq:
        build: .
        depends_on:
        - redis
        - db
        env_file:
        - .env   
        volumes:
        - .:/app
        command: bundle exec sidekiq
    api:
        build: .
        depends_on:
        - redis
        - db
        command: bundle exec rails s -b '0.0.0.0'
        env_file:
        - .env
        volumes:
        - .:/app
        ports:
        - "4000:3000"
        depends_on:
        - db
  