default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>
  wait_timeout: 300
  pool: 5
  
development:
  primary:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
test:
  <<: *default
  database: <%= ENV["DB_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  
biomark_db:
  <<: *default
  database: <%= ENV["BIOMARK_DB_NAME"] %>

